name: Deploy V2
on:
  push:
    branches: 
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            git pull origin main || (rm -rf * && git clone https://github.com{{ github.repository }}.git .)
            echo "MONGO_PASS=${{ secrets.MONGO_PASS }}" > .env
            
            # Altes Zeug stoppen (auch wenn es klemmt)
            docker compose down --remove-orphans || true
            
            # Neu starten
            docker compose up -d --build

